version: "3"

services:
    minecraft-server:
        build:
            context: ./minecraft-server
        ports: 
            - 25565:25565
        volumes:
            - minecraft-data:/papermc

volumes:
    minecraft-data:
